# -*- coding: utf-8 -*-
"""guess my number.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ODWi5_Dloohq_DND8FuFB7uIyVvRfAN3
"""

import random
attempts = 0
print('I have generated a random number between 1 and 100. You will have 10 attempts to guess that number.')
random_num = random.randint(1,100)
attempts= 0
while attempts < 10:
  guess = (int(input(f'Guess {attempts +1}:')))
  if guess == random_num:
    print('You correctly guessed my random number!')
  elif guess > random_num:
      print('Your guess is greater than my random number. Try Again.')
  else:
    guess < random_num
    print('Your guess is less than my random number. Try Again.')
  attempts +=1
if attempts == 10:
  print ('You ran out of attempts.')