# -*- coding: utf-8 -*-
"""Johnson_Marquez_speed.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nDDWcmBtZ5UEVqtGjIYlYrDBct9fPvdF
"""

speed_limit= int(input('Please enter speed limit for the road: '))
recorded_speed= int(input('Please enter vehicle\'s recorded speed:'))
speed_diff = recorded_speed - speed_limit
if recorded_speed == speed_limit:
 print('There is no fine')
elif speed_diff <= -10:
 print(' The speeding fine is $50.')
elif -10< speed_diff <20:
 print('The speeding fine is $75.')
elif 20< speed_diff <=40:
 print('The speeding fine is $150.')
elif speed_diff >40:
 print('The speeding fine is $300')