# -*- coding: utf-8 -*-
"""Johnson_Marquez_Change.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AI18fVG_YY6UxBN6tsxcreTvznEqY2TK
"""

coins = float(input('Please enter a number of cents:'))

quarters = coins//25
coins %= 25
dimes = coins//10
coins%= 10
nickels=coins//5
coins %= 5
pennies= coins//1
coins%= coins//1
print('Coins:',quarters, 'quarters', dimes, 'dimes',nickels,'nickels', pennies, 'pennies' )