# -*- coding: utf-8 -*-
"""Johnson_Marquez_Menu.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cV_4zieB4YQKstQLZWvX_broWSxj9mmr
"""

from re import S
import math
point_sale={
    'Hot Dog': 1.50,
    'Slice of Pizza': 1.99,
    'Whole Pizza': 9.95,
    'Soft Drink':0.59
}

h_value = point_sale['Hot Dog']
sp_value = point_sale ['Slice of Pizza']
wp_value = point_sale['Whole Pizza']
sd_value = point_sale['Soft Drink']

h_value = int(input('Please enter the number of Hot Dogs:'))
sp_value = int(input('Please enter the number of Pizza Slices:'))
wp_value = int(input('Please enter the number of Whole Pizzas:'))
sd_value = int(input('Please enter the number of Soft Drinks:'))

final_cost = (h_value * 1.50 + sp_value *1.99 + wp_value * 9.95 + sd_value * 0.59)
print('The total cost of the order is', (f'final cost:${final_cost:.2f}' ))