# -*- coding: utf-8 -*-
"""Johnson_Marquez_Banned_words.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hQrfw_jiSaax-ZQVXgIpabnCI2Jq1CMZ
"""

def message_filter(message):
  ban_words = [ 'Turkey', 'Dog', 'Fox', 'Cat', 'Chicken']
  #split the message into words
  bwords = message.split()
  # creating a new list without banned words
  filtered_text = [word for word in bwords if word not in ban_words]
  filtered_message = ' '.join(filtered_text)
  return filtered_message
message = input('Input Message: ')
filtered_text = message_filter(message)
out_text = print(f'Output Message: {filtered_text}')