# -*- coding: utf-8 -*-
"""Johnson_Marquez_Interstates.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pqdVd5CyCAlscglOCtGvIIEo-2RW66r_
"""

highway_num=int(input('Please enter interstate number:'))
prim = 'is primary,'
auxi= 'is auxiliary,'
if highway_num >= 1 and highway_num <=99:
  if (highway_num % 2) == 0:
    print('I-'+str(highway_num), (prim), 'going east/west.')
  else:
   print('I-' + str(highway_num), prim, 'going north/south.')
elif highway_num >=100 and highway_num <=999:
  if highway_num %100 ==0:
    print( highway_num, 'is not a valid interstate highway number.')
  elif(highway_num %2)==0:
    print('I-'+ str(highway_num), auxi, 'serving I-%d, going east/west.'% (highway_num%100))
  else:
    print('I-' +str(highway_num), auxi, 'serving I-%d, going north/south.'% (highway_num%100))
else:
   print(highway_num, 'is not a valid interstate highway number.')